name: CI/CD backend pipeline (v1)

on:
  push:
    branches:
      - master

env:
  NODE_VERSION: 24
  DOCKER_IMAGE_REPOSITORY_NAME: fercdevv/backend-sonar-node-api
  DOCKER_IMAGE_TAG: latest
  REMOTE_IMAGE_REF: fercdevv/backend-sonar-node-api:${{ github.sha }}
  TRIVY_CACHE_DIR: /tmp/trivy-cache

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout de codigo
        uses: actions/checkout@v7
      
      - name: Setup Nodejs Version
        uses: actions/setup-node@v7
        with:
          node-version: ${{ env.NODE_VERSION}}
      
      - name: Install dependencies
        run: npm ci

      - name: Ejecutar unit tests
        run: npm test
  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout de codigo
        uses: actions/checkout@v7
      
      - name: Conectar con DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build docker image and push sha tag
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_REPOSITORY_NAME }}:${{ github.sha }}

  # trivy-scan:
  #   needs: docker-build-push
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout de codigo
  #       uses: actions/checkout@v7
      
  #     - name: Setup trivy cache directory
  #       run: mkdir -p ${{ env.TRIVY_CACHE_DIR }}

  #     - name: Run Trivy Scan
  #       uses: aquasecurity/trivy-action@v0.36.0
  #       with:
  #         image-ref: ${{ env.REMOTE_IMAGE_REF }}
  #         cache-dir: ${{ env.TRIVY_CACHE_DIR }}
  #         format: 'table'
  #         exit-code: '1'
  #         ignore-unfixed: true
  #         vuln-type: 'os,library'
  #         severity: 'CRITICAL,HIGH'

  # docker-cleanup-failed-scan:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - docker-build-push
  #     - trivy-scan
  #   if: ${{ needs.trivy-scan.result == 'failure' }}

  #   steps:
  #     - name: Checkout de codigo
  #       uses: actions/checkout@v7

  #     - name: Delete sha tag from Docker Hub
  #       uses: ./.github/actions/dockerhub-delete-tag
  #       with:
  #         image_name: ${{ env.DOCKER_IMAGE_REPOSITORY_NAME }}
  #         image_tag: ${{ github.sha }}
  #         dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  docker-promote-latest:
    runs-on: ubuntu-latest
    needs: docker-build-push
    # if: ${{ needs.trivy-scan.result == 'success' }}

    steps:
      - name: Conectar con DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Pull sha image
        run: docker pull ${{ env.REMOTE_IMAGE_REF }}

      - name: Promote sha to latest
        run: |
          docker tag ${{ env.REMOTE_IMAGE_REF }} ${{ env.DOCKER_IMAGE_REPOSITORY_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
          docker push ${{ env.DOCKER_IMAGE_REPOSITORY_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
  deploy-fargate-aws:
    needs: docker-promote-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout de codigo
        uses: actions/checkout@v7

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Deploy to AWS Fargate with Cloudformation
        run: |
          aws cloudformation deploy \
            --template-file infra/ecs.yml \
            --stack-name my-fargate-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              ImageUrl=${{ env.DOCKER_IMAGE_REPOSITORY_NAME }}:${{ env.DOCKER_IMAGE_TAG }} \
              VpcId=vpc-0a3cd97730bc5332b \
              Subnets="subnet-084371090cddeab02,subnet-08ee9a8fbd634ee19,subnet-0233ac4ffbd7f09c9,subnet-081e593c9cc8b1376,subnet-0790db53816907cc4,subnet-0a8702af878a5a838"